import TL from '../../images/teamA.png'
import ND from '../../images/teamB.png'
import IR from '../../images/teamA.png'
import SL from '../../images/teamB.png'
import DIN from '../../images/teamA.png'
import SS from '../../images/teamB.png'
import YD  from '../../images/teamA.png'
import MAD from '../../images/teamB.png'
import india from '../../images/india.png'
import dashboard from '../../images/dashboard.svg'
import user from '../../images/user.svg'
import logout from '../../images/logout.svg'
import phant from '../../images/rishab.png'
import rohit from '../../images/rohit.png'
import shikar from '../../images/shikar.png'
import kohli from '../../images/kohli.png'
import thala from '../../images/rishab.png'
import aswin from '../../images/aswin.png'
import karthik from '../../images/dinesh.png'
import rahul from '../../images/rahul.png' 


const matches=(
    [
        {
            teamA:"TL-W",
            teamB:"ND_W",
            teamAimg:TL,
            teamBimg:ND,
            betted:false,
            winningstatus:"Current",
            match:"tournamentOne",
            winningcash:"10000",
            bettingcash:"100Rs"
        },
        {
            teamA:"IR-W",
            teamB:"TL-W",
            teamAimg:IR,
            teamBimg:TL,
            betted:false,
            winningstatus:"Current  ",
            match:"tournamentTwo",
            winningcash:"6000",
            bettingcash:"50Rs"

        },
        {
            teamA:"SL-W",
            teamB:"DIN_W",
            teamAimg:SL,
            teamBimg:DIN,
            betted:false,
            winningstatus:"Current  ",
            match:"tournamentThree",
            winningcash:"100000",
            bettingcash:"1000Rs"
        },
        {
            teamA:"SS-W",
            teamB:"YD_W",
            teamAimg:SS,
            teamBimg:YD,
            betted:false,
            winningstatus:"Current  ",
            match:"tournamentFour",
            winningcash:"5000",
            bettingcash:"35Rs"
        },
        {
            teamA:"YD-W",
            teamB:"SS_W",
            teamAimg:YD,
            teamBimg:SS,
            betted:false,
            winningstatus:"Current  ",
            match:"tournamentFive",
            winningcash:"10000",
            bettingcash:"100Rs"
        },
        {
            teamA:"DIN-W",
            teamB:"YD_W",
            teamAimg:DIN,
            teamBimg:YD,
            betted:false,
            winningstatus:"Current  ",
            match:"tournamentSix",
            winningcash:"67000",
            bettingcash:"650Rs"
        },
        {
            teamA:"DIN-W",
            teamB:"MAD_W",
            teamAimg:DIN,
            teamBimg:MAD,
            betted:false,
            winningstatus:"Current  ",
            match:"tournamentSeven",
            flag:true,
            winningcash:"10000",
            bettingcash:"100Rs"
        },
    ]
)

const players=(
  {
            tournamentOne:[{
                name:"N Chaiwai",
                team:"TL-W",
                role:"WK",
                points:"19.5",
                credits:9,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant

            },
            {
                name:"Raj",
                team:"TL-W",
                role:"WK",
                points:"19.5",
                credits:9.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:rahul
            },
            {
                name:"W Kingerpraset",
                team:"ND_W",
                role:"WK",
                points:"6",
                credits:8.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:thala
            },
            {
                name:"R kanoh",
                team:"TL-W",
                role:"WK",
                points:"6",
                credits:9,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:aswin
            },
            {
                name:"S amber",
                team:"ND_W",
                role:"BOWL",
                points:"6",
                credits:10,
                rolebreif:"Fast Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:kohli
            },
            {
                name:"jensmith",
                team:"TL-W",
                role:"BOWL",
                points:"6",
                credits:8,
                rolebreif:"Spin Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:karthik
            },
            {
                name:"hoooks",
                team:"ND_W",
                role:"BOWL",
                points:"6",
                credits:6,
                rolebreif:"Spin Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:{india},
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:shikar
            },

            {
                name:"shah",
                team:"TL-W",
                role:"BOWL",
                points:"6",
                credits:7.5,
                rolebreif:"Fast Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:{india},
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            } ,{
                name:"chahl",
                team:"ND_W",
                role:"AR",
                points:"6",
                credits:7.5,
                rolebreif:"All-rounder" ,
                batting:"left-handed" ,
                bowling:"left-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:{india},
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            {
                name:"eins",
                team:"TL-W",
                role:"AR",
                points:"6",
                credits:6,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },

            {
                name:"kane",
                team:"TL-W",
                role:"AR",
                points:"6",
                credits:6.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:shikar
            },
            {
                name:"wills",
                team:"TL-W",
                role:"AR",
                points:"6",
                credits:9.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            {
                name:"bolin",
                team:"ND_W",
                role:"BAT",
                points:"6",
                credits:5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            {
                name:"bills",
                team:"TL-W",
                role:"BAT",
                points:"6",
                credits:4,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:shikar
            }, {
                name:"amith",
                team:"ND_W",
                role:"BAT",
                points:"6",
                credits:10,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            }, {
                name:"sharma",
                team:"TL-W",
                role:"BAT",
                points:"6",
                credits:9,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:shikar
            }
        
        ],



            tournamentTwo:[ {
                name:"N Chaiwai",
                team:"TL-W",
                role:"WK",
                points:"19.5",
                credits:9.5
            },
            {
                name:"Raj",
                team:"TL-W",
                role:"WK",
                points:"19.5",
                credits:9.5
            },
            {
                name:"W Kingerpraset",
                team:"TL-W",
                role:"BAT",
                points:"6",
                credits:8
                        },
            {
                name:"R kanoh",
                team:"TL-W",
                role:"AR",
                points:"6",
                credits:8
            },
            {   name:"S laomi",
                team:"TL-W",
                role:"BOWL",
                points:"6",
                credits:8
            }],

            tournamentThree:[{
                name:"N Chaiwai",
                team:"TL-W",
                role:"WK",
                points:"19.5",
                credits:9,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant

            },
            {
                name:"Raj",
                team:"TL-W",
                role:"WK",
                points:"19.5",
                credits:9.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:shikar
            },
            {
                name:"W Kingerpraset",
                team:"ND_W",
                role:"WK",
                points:"6",
                credits:8.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            {
                name:"jensmith",
                team:"TL-W",
                role:"BOWL",
                points:"6",
                credits:8,
                rolebreif:"Spin Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            {
                name:"R kanoh",
                team:"TL-W",
                role:"WK",
                points:"6",
                credits:9,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            {
                name:"S amber",
                team:"ND_W",
                role:"BOWL",
                points:"6",
                credits:10,
                rolebreif:"Fast Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:rohit
            },
            
            {
                name:"hoooks",
                team:"ND_W",
                role:"BOWL",
                points:"6",
                credits:6,
                rolebreif:"Spin Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:{india},
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },

            {
                name:"shah",
                team:"TL-W",
                role:"BOWL",
                points:"6",
                credits:7.5,
                rolebreif:"Fast Bowler" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:{india},
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:rohit
            },{
                name:"kane",
                team:"TL-W",
                role:"AR",
                points:"6",
                credits:6.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            } ,
            {
                name:"eins",
                team:"TL-W",
                role:"AR",
                points:"6",
                credits:6,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:rohit
            }
            ,{
                name:"chahl",
                team:"ND_W",
                role:"AR",
                points:"6",
                credits:7.5,
                rolebreif:"All-rounder" ,
                batting:"left-handed" ,
                bowling:"left-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:{india},
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },{
                name:"sharma",
                team:"TL-W",
                role:"BAT",
                points:"6",
                credits:9,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            
            {
                name:"wills",
                team:"TL-W",
                role:"AR",
                points:"6",
                credits:9.5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
          
            {
                name:"bills",
                team:"TL-W",
                role:"BAT",
                points:"6",
                credits:4,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:rohit
            }, {
                name:"amith",
                team:"ND_W",
                role:"BAT",
                points:"6",
                credits:10,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            },
            {
                name:"bolin",
                team:"ND_W",
                role:"BAT",
                points:"6",
                credits:5,
                rolebreif:"Wicket Keeper" ,
                batting:"Right-handed" ,
                bowling:"Right-handed",
                strikerate:100.5,
                fiffty:50,
                hundreds:10,
                country:"India",
                score:0,
                wicket:0,
                countryImg:india,
                yoe:"10",
                Age:"35",
                Dob:"10-10-10",
                average:"30",
                odi:"78",
                test:"30",
                t20:"120",
                playerimg:phant
            }
        
        ],
        tournamentFour:[{
            name:"N Chaiwai",
            team:"TL-W",
            role:"WK",
            points:"19.5",
            credits:9,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant

        },
        {
            name:"Raj",
            team:"TL-W",
            role:"WK",
            points:"19.5",
            credits:9.5,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:rahul
        },
        {
            name:"W Kingerpraset",
            team:"ND_W",
            role:"WK",
            points:"6",
            credits:8.5,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        },
        {
            name:"R kanoh",
            team:"TL-W",
            role:"WK",
            points:"6",
            credits:9,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        },
        {
            name:"S amber",
            team:"ND_W",
            role:"BOWL",
            points:"6",
            credits:10,
            rolebreif:"Fast Bowler" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:rohit
        },
        {
            name:"jensmith",
            team:"TL-W",
            role:"BOWL",
            points:"6",
            credits:8,
            rolebreif:"Spin Bowler" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        },
        {
            name:"hoooks",
            team:"ND_W",
            role:"BOWL",
            points:"6",
            credits:6,
            rolebreif:"Spin Bowler" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:{india},
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:thala
        },

        {
            name:"shah",
            team:"TL-W",
            role:"BOWL",
            points:"6",
            credits:7.5,
            rolebreif:"Fast Bowler" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:{india},
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        } ,{
            name:"chahl",
            team:"ND_W",
            role:"AR",
            points:"6",
            credits:7.5,
            rolebreif:"All-rounder" ,
            batting:"left-handed" ,
            bowling:"left-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:{india},
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:thala
        },
        ,{
            name:"eins",
            team:"TL-W",
            role:"AR",
            points:"6",
            credits:6,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        },

        ,{
            name:"kane",
            team:"TL-W",
            role:"AR",
            points:"6",
            credits:6.5,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:thala
        },
        ,{
            name:"wills",
            team:"TL-W",
            role:"AR",
            points:"6",
            credits:9.5,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        },
        ,{
            name:"bolin",
            team:"ND_W",
            role:"BAT",
            points:"6",
            credits:5,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        },
        {
            name:"bills",
            team:"TL-W",
            role:"BAT",
            points:"6",
            credits:4,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        }, {
            name:"amith",
            team:"ND_W",
            role:"BAT",
            points:"6",
            credits:10,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        }, {
            name:"sharma",
            team:"TL-W",
            role:"BAT",
            points:"6",
            credits:9,
            rolebreif:"Wicket Keeper" ,
            batting:"Right-handed" ,
            bowling:"Right-handed",
            strikerate:100.5,
            fiffty:50,
            hundreds:10,
            country:"India",
            score:0,
            wicket:0,
            countryImg:india,
            yoe:"10",
            Age:"35",
            Dob:"10-10-10",
            average:"30",
            odi:"78",
            test:"30",
            t20:"120",
            playerimg:phant
        }
    
    ],

    tournamentFive:[{
        name:"N Chaiwai",
        team:"TL-W",
        role:"WK",
        points:"19.5",
        credits:9,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant

    },
    {
        name:"Raj",
        team:"TL-W",
        role:"WK",
        points:"19.5",
        credits:9.5,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:rahul
    },
    {
        name:"W Kingerpraset",
        team:"ND_W",
        role:"WK",
        points:"6",
        credits:8.5,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    {
        name:"R kanoh",
        team:"TL-W",
        role:"WK",
        points:"6",
        credits:9,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    {
        name:"S amber",
        team:"ND_W",
        role:"BOWL",
        points:"6",
        credits:10,
        rolebreif:"Fast Bowler" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    {
        name:"jensmith",
        team:"TL-W",
        role:"BOWL",
        points:"6",
        credits:8,
        rolebreif:"Spin Bowler" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    {
        name:"hoooks",
        team:"ND_W",
        role:"BOWL",
        points:"6",
        credits:6,
        rolebreif:"Spin Bowler" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:{india},
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },

    {
        name:"shah",
        team:"TL-W",
        role:"BOWL",
        points:"6",
        credits:7.5,
        rolebreif:"Fast Bowler" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:{india},
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    } ,{
        name:"chahl",
        team:"ND_W",
        role:"AR",
        points:"6",
        credits:7.5,
        rolebreif:"All-rounder" ,
        batting:"left-handed" ,
        bowling:"left-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:{india},
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    ,{
        name:"eins",
        team:"TL-W",
        role:"AR",
        points:"6",
        credits:6,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },

    ,{
        name:"kane",
        team:"TL-W",
        role:"AR",
        points:"6",
        credits:6.5,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    ,{
        name:"wills",
        team:"TL-W",
        role:"AR",
        points:"6",
        credits:9.5,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    ,{
        name:"bolin",
        team:"ND_W",
        role:"BAT",
        points:"6",
        credits:5,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    },
    {
        name:"bills",
        team:"TL-W",
        role:"BAT",
        points:"6",
        credits:4,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    }, {
        name:"amith",
        team:"ND_W",
        role:"BAT",
        points:"6",
        credits:10,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    }, {
        name:"sharma",
        team:"TL-W",
        role:"BAT",
        points:"6",
        credits:9,
        rolebreif:"Wicket Keeper" ,
        batting:"Right-handed" ,
        bowling:"Right-handed",
        strikerate:100.5,
        fiffty:50,
        hundreds:10,
        country:"India",
        score:0,
        wicket:0,
        countryImg:india,
        yoe:"10",
        Age:"35",
        Dob:"10-10-10",
        average:"30",
        odi:"78",
        test:"30",
        t20:"120",
        playerimg:phant
    }

],



  }
)

const squadContainers=(
    [
    {
        container:"WK-container",
        role:"WK",
        position:"WICKET KEEPER"
    },
    {
        container:"BAT-container",
        role:"BAT",
        position:"BATSMAN"
    },
    {
        container:"AR-container",
        role:"AR",
        position:"ALL ROUNDER"
    },
    {
        container:"BOWL-container",
        role:"BOWL",
        position:"BOWLER"
    }
])


const userMenu=(
    [
        {
            icon:dashboard,
            menu:"Dashboard",
            link:"/Dashboard"
        },
        {
            icon:user,
            menu:"Personal Details",
            link:"/personal"
        }, {
            icon:logout,
            menu:"Logout",
            link:"/"
        }
        

    ]
)

export {matches,players,squadContainers,userMenu}